version: '3'

services:
  frontend:
    networks:
      - app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    tty: true  
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      
networks:
  app:
    driver: bridge